language: java

os: 
  - linux
  - osx

dist: trusty

jdk:
  - openjdk11
  - openjdk10
  - openjdk9
  - oraclejdk11
  # oraclejdk10 is deprecated
  - oraclejdk9

script: travis_wait 15 mvn --batch-mode --file=pom.xml --update-snapshots verify
