language: java

os: 
  - linux
  - osx

jdk:
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  - oraclejdk11
  # oraclejdk10 not supported by Travis CI
  # oraclejdk9 can't find the Maven plugin maven-failsafe-plugin


