# This workflow will build a Java project with Maven (Mac OS Latest)
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven (Mac OS Latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        java: [ '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19' ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Cache Maven packages
        uses: actions/cache@main
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test with Maven
        run: mvn --batch-mode --file=pom.xml --update-snapshots verify
